[supervisord]
nodaemon=true
user=booking-ps.bellukstudio.my.id
logfile=/var/www/booking-ps.bellukstudio.my.id/storage/logs/supervisord.log
pidfile=/var/www/booking-ps.bellukstudio.my.id/storage/supervisord.pid
